spring.application.name=auth-service
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3307/auth_db
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=ceci-est-une-cle-secrete-tres-longue-pour-signer-les-tokens-jwt-bank-platform-2026
jwt.expiration=86400000


# Configuration Mailtrap pour l'envoi des codes OTP (2FA)
# Remplace host/port/username/password par les valeurs affichees dans ton dashboard Mailtrap
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=82a73b7691dd2c
spring.mail.password=3a1d10a1123119
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Duree de validite du code OTP en minutes
otp.expiration-minutes=5

# Configuration RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
rabbitmq.exchange.user=user.exchange
rabbitmq.routingkey.user-created=user.created